workflows:
  android-app:
    name: Android Wallet Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Build debug APK
        working_directory: android-app
        script: ./gradlew assembleDebug
    artifacts:
      - android-app/app/build/outputs/**/*.apk
